package com.example.harry.tujuhkeajaibandunia;

import java.util.ArrayList;

public class KeajaibanData {
    public static String[][] data = new String[][]{
            {"Piramida Agung Giza", "Giza, Mesir", "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/450px-Kheops-Pyramid.jpg","Afrika Utara","29°58′45″N 31°08′04″E","Piramida Agung Giza (juga dikenal sebagai Piramida Khufu atau Piramida Cheops) adalah yang tertua dan terbesar dari tiga piramida di kompleks piramida Giza yang berbatasan dengan apa yang sekarang bernama El Giza, Mesir. Ini adalah yang tertua dari Tujuh Keajaiban Dunia Kuno, dan satu-satunya yang tetap utuh."},
            {"Tembok Besar China", "China", "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/The_Great_Wall_of_China_at_Jinshanling-edit.jpg/360px-The_Great_Wall_of_China_at_Jinshanling-edit.jpg","Asia Pasifik","40.68°N 117.23°E","Tembok Besar Tiongkok adalah serangkaian benteng yang terbuat dari batu, batu bata, tanah bercabang, kayu, dan bahan-bahan lainnya, umumnya dibangun di sepanjang garis timur-ke-barat melintasi perbatasan utara Tiongkok yang bersejarah untuk melindungi negara-negara Cina dan kekaisaran terhadap penggerebekan dan invasi dari berbagai kelompok nomaden di Stepa Eurasia dengan tujuan ekspansi."},
            {"Petra", "Yordania", "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/The_Monastery%2C_Petra%2C_Jordan8.jpg/330px-The_Monastery%2C_Petra%2C_Jordan8.jpg","Timur Tengah","30°19′43″N 35°26′31″E","Petra terletak di lereng Jabal Al-Madbah di lembah di antara gunung-gunung yang membentuk sisi timur lembah Arabah yang membentang dari Laut Mati ke Teluk Aqaba.Petra diyakini telah diselesaikan pada awal 9000 SM, dan itu mungkin didirikan pada abad ke-4 SM sebagai ibu kota Kerajaan Nabatea. Orang Nabatea adalah orang Arab nomaden yang berinvestasi di kedekatan Petra dengan rute perdagangan dengan menjadikannya sebagai pusat perdagangan regional utama."},
            {"Colloseum", "Roma, Italia", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg/375px-Colosseum_in_Rome%2C_Italy_-_April_2007.jpg","Eropa","41°54′N 12°30′E","Colosseum atau Coliseum (/ kɒləˈsiːəm / kol-ə-SEE-əm), juga dikenal sebagai Flavian Amphitheatre (Bahasa Latin: Amphitheatrum Flavium; bahasa Itali: Anfiteatro Flavio [aŋfiteˈaːtro ˈflaːvjo] atau Colosseo). pusat kota Roma, Italia. Dibangun dari travertine, tufa, dan beton berwajah bata, itu adalah ampiteater terbesar yang pernah dibangun. Colosseum terletak di sebelah timur Forum Romawi. Konstruksi dimulai di bawah kaisar Vespasianus pada 72 M, dan selesai pada 80 M di bawah penggantinya dan pewaris Titus. Modifikasi lebih lanjut dilakukan pada masa pemerintahan Domitianus (81-96). Tiga kaisar ini dikenal sebagai dinasti Flavian, dan amfiteater dinamai dalam bahasa Latin karena hubungannya dengan nama keluarga mereka (Flavius)."},
            {"Chichen Itza", "Yucatan, Mexico", "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/540px-Chichen_Itza_3.jpg","Amerika Latin dan Caribia","20°40′59″N 88°34′7″W","Chichen Itza adalah kota besar pra-Kolombia yang dibangun oleh orang-orang Maya dari periode Terminal Classic. Situs arkeologi terletak di Kota Tinúm, Negara Bagian Yucatán, Meksiko. Chichen Itza adalah titik fokus utama di Dataran Rendah Maya Utara dari Late Classic (c. 600-900 M) melalui Terminal Classic (c. 800-900 M) dan masuk ke bagian awal periode Postclassic (c. 900 M). –1200). Situs ini menunjukkan banyak gaya arsitektur, mengingatkan pada gaya yang terlihat di Meksiko tengah dan gaya Puuc dan Chenes dari dataran rendah Maya Utara. Kehadiran gaya Meksiko tengah pernah dianggap mewakili migrasi langsung atau bahkan penaklukan dari Meksiko tengah, tetapi sebagian besar interpretasi kontemporer memandang kehadiran gaya-gaya non-Maya ini lebih sebagai hasil dari difusi budaya."},
            {"Machu Picchu", "Cuzco, Peru", "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/80_-_Machu_Picchu_-_Juin_2009_-_edit.2.jpg/450px-80_-_Machu_Picchu_-_Juin_2009_-_edit.2.jpg","Amerika Latin dan Caribia","13°09′48″S 72°32′44″W","Machu Picchu (/ ˈmɑːtʃuː ˈpiːktʃuːor / ˈpiːtʃuː /; Bahasa Spanyol: [ˈmatʃu ˈpi (k) tʃu]; Quechua: Machu Pikchu [ˈmɑtʃu ˈpiktʃu]) adalah gunung ke-15 di pegunungan Corda di bagian selatan Peru, terletak di pegunungan Corda di bagian timur Peru, terletak di pegunungan Corda di bagian selatan Peru, terletak di pegunungan Corda di bagian selatan Peru, terletak di pegunungan Corda di bagian timur Peru, terletak di pegunungan Corda di bagian timur Peru, di benteng di Corda di Peru, di bagian selatan Peru, terletak di pegunungan Corda di bagian timur Peru, terletak di pegunungan Corda di Peru. punggungan 2.430 meter (7.970 kaki) di atas permukaan laut. Terletak di Wilayah Cusco, Provinsi Urubamba, Distrik Machupicchu di Peru, di atas Lembah Suci, yang 80 kilometer (50 mil) barat laut Cuzco dan melaluinya Sungai Urubamba mengalir , yang memotong Cordillera dan berasal ngarai dengan iklim gunung tropis."},
            {"Taj Mahal", "Agra, Uttar Pradesh, India", "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Taj_Mahal_%28Edited%29.jpeg/375px-Taj_Mahal_%28Edited%29.jpeg","Asia Selatan","27°10′30″N 78°02′31″E","Taj Mahal (/ ʒtɑːdʒ məˈhɑːl, ˌtɑːʒ- /; Hindi: ताज महल [taːdʒ ˈmɛːɦ (ə) l], yang berarti \"Mahkota Istana\") adalah makam marmer putih gading di tepi selatan sungai Yamuna di sungai Kota Agra di India. Itu ditugaskan pada 1632 oleh kaisar Mughal, Shah Jahan (memerintah 1628-1658), untuk menampung makam istri kesayangannya, Mumtaz Mahal. Itu juga rumah makam Shah Jahan, pembangun. Makam tersebut adalah pusat dari kompleks seluas 17 hektar (42 hektar), yang meliputi sebuah masjid dan wisma, dan terletak di taman-taman formal yang dibatasi pada tiga sisi oleh sebuah dinding yang terpukul. Konstruksi makam pada dasarnya selesai pada tahun 1643 tetapi pekerjaan berlanjut pada fase-fase lain proyek selama 10 tahun berikutnya. Kompleks Taj Mahal diyakini telah selesai seluruhnya pada tahun 1653 dengan biaya yang diperkirakan saat itu sekitar 32 juta rupee, yang pada tahun 2015 akan menjadi sekitar 52,8 miliar rupee (US $ 827 juta). Proyek konstruksi mempekerjakan sekitar 20.000 pengrajin di bawah bimbingan dewan arsitek yang dipimpin oleh arsitek istana kepada kaisar, Ustad Ahmad Lahauri."}
    };

    public static ArrayList<Keajaiban> getListData(){
        Keajaiban keajaiban = null;
        ArrayList<Keajaiban> list = new ArrayList<>();
        for (String[] aData : data){
            keajaiban = new Keajaiban();
            keajaiban.setName(aData[0]);
            keajaiban.setRemarks(aData[1]);
            keajaiban.setPhoto(aData[2]);
            keajaiban.setRegional(aData[3]);
            keajaiban.setKoordinat(aData[4]);
            keajaiban.setKeterangan(aData[5]);

            list.add(keajaiban);
        }
        return list;
    }
}
